/*
 * Sinonimia dictionary — SPANISH.
 * Hard or technical words (administrative, legal, health) explained in plain
 * language, based on "lenguaje claro" (plain-language) glossaries and
 * patient-facing medical glossaries (IVAP, Red de Lenguaje Claro, RAE,
 * clinical glossaries).
 *
 * This file is ONLY the Spanish-language content. The interface's fixed
 * texts (buttons, messages...) live in js/i18n.js. See js/data.en.js for the
 * same dictionary in English and for how to add a new language.
 *
 * To add a new word, copy a `{ ... }` block and fill in its fields. No other
 * file needs to change: the site reads this list automatically.
 *
 * Fields (kept in Spanish on purpose — see ARCHITECTURE.md's "Naming
 * exceptions" for why the schema keys below are not translated):
 *  id          -> short id, no spaces or accents, unique (used in the word's
 *                 link). Doesn't need to match the same concept's id in
 *                 another language.
 *  palabra     -> the word as normally written (used as the title and in the list)
 *  imagen      -> { id, alt } supporting pictogram. "id" is the pictogram's id
 *                 on ARASAAC (arasaac.org) and "alt" is its text description
 *                 (in this file's language). The image is stored at
 *                 img/<imagen.id>.png — several words or languages can share
 *                 the same pictogram if they use the same "id".
 *  definicion  -> short, plain explanation, without using other hard words
 *  sinonimos   -> plain words or phrases that mean roughly the same thing
 *  ejemplo     -> { palabra, texto } an everyday sentence; "palabra" is the
 *                 EXACT form (with its conjugation or gender) that appears
 *                 inside "texto"
 *  ejemploSinonimo -> the SAME sentence, swapping that form for its plain version
 *  situacion   -> key shared across all languages: "tramites", "salud",
 *                 "vida-diaria", "finanzas", "vivienda", "trabajo", or
 *                 "legal" (see PRODUCT.md for what each covers). Their
 *                 on-screen labels (Trámites/Procedures, etc.) live in
 *                 js/i18n.js.
 */

window.DICCIONARIOS = window.DICCIONARIOS || {};
DICCIONARIOS.es = [
  // --- Administration and paperwork (plain language) ---
  {
    id: "subsanar",
    palabra: "Subsanar",
    imagen: { id: 28189, alt: "Una mano corrige un error escrito en un papel" },
    definicion: "Arreglar un error en un papel. Poner lo que falta.",
    sinonimos: ["corregir", "arreglar", "completar"],
    ejemplo: { palabra: "subsane", texto: "El ayuntamiento le pide que subsane la solicitud antes del viernes." },
    ejemploSinonimo: { palabra: "corrija", texto: "El ayuntamiento le pide que corrija la solicitud antes del viernes." },
    situacion: "tramites",
  },
  {
    id: "desistir",
    palabra: "Desistir",
    imagen: { id: 7195, alt: "Una persona hace un gesto de parar con la mano" },
    definicion: "Dejar de pedir algo. No seguir con un trámite.",
    sinonimos: ["renunciar", "abandonar"],
    ejemplo: { palabra: "desiste", texto: "Si no entrega los papeles, se entenderá que desiste de la solicitud." },
    ejemploSinonimo: { palabra: "renuncia a", texto: "Si no entrega los papeles, se entenderá que renuncia a la solicitud." },
    situacion: "tramites",
  },
  {
    id: "requerimiento",
    palabra: "Requerimiento",
    imagen: { id: 2688, alt: "Un sobre con una carta" },
    definicion: "Un papel oficial. Te pide hacer algo.",
    sinonimos: ["aviso", "petición formal"],
    ejemplo: { palabra: "requerimiento", texto: "Recibió un requerimiento de Hacienda para presentar más documentos." },
    ejemploSinonimo: { palabra: "aviso", texto: "Recibió un aviso de Hacienda para presentar más documentos." },
    situacion: "tramites",
  },
  {
    id: "incurso",
    palabra: "Incurso",
    imagen: { id: 10173, alt: "Un policía pone una multa a un coche" },
    definicion: "Has hecho algo mal. Por eso se abre un caso contra ti.",
    sinonimos: ["implicado", "sometido a expediente"],
    ejemplo: { palabra: "incurso", texto: "El conductor está incurso en un expediente por exceso de velocidad." },
    ejemploSinonimo: { palabra: "implicado", texto: "El conductor está implicado en un expediente por exceso de velocidad." },
    situacion: "legal",
  },
  {
    id: "interponer",
    palabra: "Interponer",
    imagen: { id: 14006, alt: "Una mano presenta un papel firmado" },
    definicion: "Presentar una queja de forma oficial.",
    sinonimos: ["presentar"],
    ejemplo: { palabra: "interponer", texto: "Puede interponer un recurso si no está de acuerdo con la decisión." },
    ejemploSinonimo: { palabra: "presentar", texto: "Puede presentar un recurso si no está de acuerdo con la decisión." },
    situacion: "legal",
  },
  {
    id: "comparecer",
    palabra: "Comparecer",
    imagen: { id: 11291, alt: "Un juez con un mazo" },
    definicion: "Ir en persona a un lugar. Te llama un juez o una autoridad.",
    sinonimos: ["presentarse", "acudir"],
    ejemplo: { palabra: "comparecer", texto: "El testigo debe comparecer en el juzgado el próximo lunes." },
    ejemploSinonimo: { palabra: "presentarse", texto: "El testigo debe presentarse en el juzgado el próximo lunes." },
    situacion: "legal",
  },
  {
    id: "notificacion",
    palabra: "Notificación",
    imagen: { id: 2688, alt: "Un sobre con una carta" },
    definicion: "Un aviso oficial. Te cuenta una decisión.",
    sinonimos: ["aviso", "comunicación"],
    ejemplo: { palabra: "notificación", texto: "Le llegó una notificación del juzgado a su casa." },
    ejemploSinonimo: { palabra: "aviso", texto: "Le llegó un aviso del juzgado a su casa." },
    situacion: "tramites",
  },
  {
    id: "resolucion",
    palabra: "Resolución",
    imagen: { id: 37861, alt: "Dos personas se ponen de acuerdo" },
    definicion: "Una decisión oficial. La toma un juez o una autoridad.",
    sinonimos: ["decisión"],
    ejemplo: { palabra: "resolución", texto: "La resolución del ayuntamiento llegó por correo esta semana." },
    ejemploSinonimo: { palabra: "decisión", texto: "La decisión del ayuntamiento llegó por correo esta semana." },
    situacion: "tramites",
  },
  {
    id: "alegar",
    palabra: "Alegar",
    imagen: { id: 8579, alt: "Una persona explica algo" },
    definicion: "Explicar tus motivos. Dar tus razones.",
    sinonimos: ["argumentar", "explicar"],
    ejemplo: { palabra: "alegó", texto: "En el juicio, el abogado alegó que su cliente no estaba presente ese día." },
    ejemploSinonimo: { palabra: "explicó", texto: "En el juicio, el abogado explicó que su cliente no estaba presente ese día." },
    situacion: "legal",
  },
  {
    id: "fehaciente",
    palabra: "Fehaciente",
    imagen: { id: 12317, alt: "Una mano firma un papel" },
    definicion: "Que se puede comprobar. No deja dudas.",
    sinonimos: ["seguro", "comprobado"],
    ejemplo: { palabra: "fehaciente", texto: "Necesita un documento fehaciente que demuestre dónde vive." },
    ejemploSinonimo: { palabra: "seguro", texto: "Necesita un documento seguro que demuestre dónde vive." },
    situacion: "legal",
  },
  {
    id: "cautelar",
    palabra: "Cautelar",
    imagen: { id: 6192, alt: "Unas personas se protegen juntas" },
    definicion: "Que sirve para proteger. Se usa mientras se resuelve un problema.",
    sinonimos: ["preventivo", "de protección"],
    ejemplo: { palabra: "cautelar", texto: "El juez tomó una medida cautelar para proteger a la familia." },
    ejemploSinonimo: { palabra: "preventiva", texto: "El juez tomó una medida preventiva para proteger a la familia." },
    situacion: "legal",
  },
  {
    id: "usufructo",
    palabra: "Usufructo",
    imagen: { id: 2317, alt: "Una casa" },
    definicion: "Usar algo y aprovecharlo. Aunque no sea tuyo.",
    sinonimos: ["uso y disfrute"],
    ejemplo: { palabra: "usufructo", texto: "La abuela dejó a su hija el usufructo de la casa de la playa." },
    ejemploSinonimo: { palabra: "uso y disfrute", texto: "La abuela dejó a su hija el uso y disfrute de la casa de la playa." },
    situacion: "legal",
  },
  {
    id: "litigio",
    palabra: "Litigio",
    imagen: { id: 37786, alt: "Dos personas discuten" },
    definicion: "Una pelea legal entre dos personas. La resuelve un juez.",
    sinonimos: ["pleito", "conflicto legal"],
    ejemplo: { palabra: "litigio", texto: "Los dos vecinos tienen un litigio por el muro del jardín." },
    ejemploSinonimo: { palabra: "pleito", texto: "Los dos vecinos tienen un pleito por el muro del jardín." },
    situacion: "legal",
  },

  // --- Health (patient-facing medical glossaries) ---
  {
    id: "afasia",
    palabra: "Afasia",
    imagen: { id: 3345, alt: "Dos personas hablan" },
    definicion: "Cuesta hablar o entender. Pasa por un problema en el cerebro.",
    sinonimos: ["pérdida del habla"],
    ejemplo: { palabra: "afasia", texto: "Después del ictus, el abuelo tiene afasia y le cuesta encontrar las palabras." },
    ejemploSinonimo: { palabra: "pérdida del habla", texto: "Después del ictus, el abuelo tiene pérdida del habla y le cuesta encontrar las palabras." },
    situacion: "salud",
  },
  {
    id: "cefalea",
    palabra: "Cefalea",
    imagen: { id: 28651, alt: "Una persona con dolor de cabeza" },
    definicion: "Dolor de cabeza.",
    sinonimos: ["dolor de cabeza"],
    ejemplo: { palabra: "cefalea", texto: "El médico le recetó una pastilla para la cefalea." },
    ejemploSinonimo: { palabra: "dolor de cabeza", texto: "El médico le recetó una pastilla para el dolor de cabeza." },
    situacion: "salud",
  },
  {
    id: "disnea",
    palabra: "Disnea",
    imagen: { id: 34409, alt: "Una persona respira" },
    definicion: "Cuesta respirar. Sientes que te falta el aire.",
    sinonimos: ["ahogo", "falta de aire"],
    ejemplo: { palabra: "disnea", texto: "Subir las escaleras le provoca disnea desde hace unos días." },
    ejemploSinonimo: { palabra: "ahogo", texto: "Subir las escaleras le provoca ahogo desde hace unos días." },
    situacion: "salud",
  },
  {
    id: "disfagia",
    palabra: "Disfagia",
    imagen: { id: 27099, alt: "La garganta de una persona" },
    definicion: "Cuesta tragar la comida o el agua.",
    sinonimos: ["dificultad para tragar"],
    ejemplo: { palabra: "disfagia", texto: "La logopeda ayuda a las personas con disfagia a comer sin atragantarse." },
    ejemploSinonimo: { palabra: "dificultad para tragar", texto: "La logopeda ayuda a las personas con dificultad para tragar a comer sin atragantarse." },
    situacion: "salud",
  },
  {
    id: "edema",
    palabra: "Edema",
    imagen: { id: 3405, alt: "Un tobillo hinchado" },
    definicion: "El cuerpo se hincha. Se junta líquido bajo la piel.",
    sinonimos: ["hinchazón"],
    ejemplo: { palabra: "edema", texto: "El tobillo tiene un edema después del golpe." },
    ejemploSinonimo: { palabra: "una hinchazón", texto: "El tobillo tiene una hinchazón después del golpe." },
    situacion: "salud",
  },
  {
    id: "bradicardia",
    palabra: "Bradicardia",
    imagen: { id: 2715, alt: "Un corazón" },
    definicion: "El corazón late más despacio de lo normal.",
    sinonimos: ["latido lento del corazón"],
    ejemplo: { palabra: "bradicardia", texto: "El cardiólogo detectó bradicardia en la última revisión." },
    ejemploSinonimo: { palabra: "un latido lento", texto: "El cardiólogo detectó un latido lento en la última revisión." },
    situacion: "salud",
  },
  {
    id: "cianosis",
    palabra: "Cianosis",
    imagen: { id: 2840, alt: "La piel de una mano" },
    definicion: "La piel o los labios se ponen azules. Falta oxígeno.",
    sinonimos: ["color azulado de la piel"],
    ejemplo: { palabra: "cianosis", texto: "El bebé tenía cianosis en los labios y lo llevaron corriendo al hospital." },
    ejemploSinonimo: { palabra: "color azulado", texto: "El bebé tenía color azulado en los labios y lo llevaron corriendo al hospital." },
    situacion: "salud",
  },
  {
    id: "astenia",
    palabra: "Astenia",
    imagen: { id: 2314, alt: "Una cara cansada" },
    definicion: "Mucho cansancio. Falta de fuerzas varios días.",
    sinonimos: ["falta de energía", "debilidad"],
    ejemplo: { palabra: "astenia", texto: "Con el cambio de estación, mucha gente nota astenia primaveral." },
    ejemploSinonimo: { palabra: "falta de energía", texto: "Con el cambio de estación, mucha gente nota falta de energía primaveral." },
    situacion: "salud",
  },
  {
    id: "disuria",
    palabra: "Disuria",
    imagen: { id: 3429, alt: "Una persona va al baño" },
    definicion: "Duele al hacer pis.",
    sinonimos: ["dolor al orinar"],
    ejemplo: { palabra: "disuria", texto: "Fue al médico porque sentía disuria desde hacía dos días." },
    ejemploSinonimo: { palabra: "dolor al orinar", texto: "Fue al médico porque sentía dolor al orinar desde hacía dos días." },
    situacion: "salud",
  },
  {
    id: "eritema",
    palabra: "Eritema",
    imagen: { id: 2840, alt: "La piel de una mano" },
    definicion: "La piel se pone roja. Puede picar un poco.",
    sinonimos: ["enrojecimiento de la piel"],
    ejemplo: { palabra: "eritema", texto: "La crema nueva le dejó un eritema en el brazo." },
    ejemploSinonimo: { palabra: "un enrojecimiento", texto: "La crema nueva le dejó un enrojecimiento en el brazo." },
    situacion: "salud",
  },
  {
    id: "dermatitis",
    palabra: "Dermatitis",
    imagen: { id: 2840, alt: "La piel de una mano" },
    definicion: "La piel se irrita. Pica o sale rojez.",
    sinonimos: ["irritación de la piel"],
    ejemplo: { palabra: "dermatitis", texto: "El niño tiene dermatitis en los brazos por el calor." },
    ejemploSinonimo: { palabra: "irritación de la piel", texto: "El niño tiene irritación de la piel en los brazos por el calor." },
    situacion: "salud",
  },
  {
    id: "gastritis",
    palabra: "Gastritis",
    imagen: { id: 3309, alt: "El estómago" },
    definicion: "El estómago se inflama. Duele después de comer.",
    sinonimos: ["inflamación del estómago"],
    ejemplo: { palabra: "gastritis", texto: "Le diagnosticaron gastritis y ahora evita el café y las comidas picantes." },
    ejemploSinonimo: { palabra: "una inflamación del estómago", texto: "Le diagnosticaron una inflamación del estómago y ahora evita el café y las comidas picantes." },
    situacion: "salud",
  },
  {
    id: "artrosis",
    palabra: "Artrosis",
    imagen: { id: 2810, alt: "Una rodilla" },
    definicion: "Las articulaciones se desgastan. Duelen y cuesta moverlas.",
    sinonimos: ["desgaste de las articulaciones"],
    ejemplo: { palabra: "artrosis", texto: "La abuela tiene artrosis en las rodillas y le cuesta subir escaleras." },
    ejemploSinonimo: { palabra: "un desgaste en las articulaciones", texto: "La abuela tiene un desgaste en las articulaciones de las rodillas y le cuesta subir escaleras." },
    situacion: "salud",
  },
  {
    id: "artritis",
    palabra: "Artritis",
    imagen: { id: 2928, alt: "Una mano" },
    definicion: "Las articulaciones se inflaman. Duelen y se hinchan.",
    sinonimos: ["inflamación de las articulaciones"],
    ejemplo: { palabra: "artritis", texto: "Por las mañanas, la artritis le dificulta cerrar las manos." },
    ejemploSinonimo: { palabra: "la inflamación de las articulaciones", texto: "Por las mañanas, la inflamación de las articulaciones le dificulta cerrar las manos." },
    situacion: "salud",
  },
  {
    id: "biopsia",
    palabra: "Biopsia",
    imagen: { id: 32112, alt: "Pruebas de laboratorio" },
    definicion: "Una prueba médica. Se coge un trozo pequeño del cuerpo para mirarlo.",
    sinonimos: ["prueba de tejido"],
    ejemplo: { palabra: "biopsia", texto: "Le hicieron una biopsia del lunar para asegurarse de que estaba bien." },
    ejemploSinonimo: { palabra: "una prueba", texto: "Le hicieron una prueba del lunar para asegurarse de que estaba bien." },
    situacion: "salud",
  },
  {
    id: "luxacion",
    palabra: "Luxación",
    imagen: { id: 2972, alt: "Un hueso" },
    definicion: "Un hueso se sale de su sitio.",
    sinonimos: ["hueso fuera de sitio"],
    ejemplo: { palabra: "luxación", texto: "Se cayó jugando al fútbol y tiene una luxación de hombro." },
    ejemploSinonimo: { palabra: "el hombro fuera de sitio", texto: "Se cayó jugando al fútbol y tiene el hombro fuera de sitio." },
    situacion: "salud",
  },
  {
    id: "ambulatorio",
    palabra: "Ambulatorio",
    imagen: { id: 3116, alt: "Un hospital" },
    definicion: "No hace falta quedarse en el hospital. Vuelves a casa el mismo día.",
    sinonimos: ["sin ingreso"],
    ejemplo: { palabra: "ambulatoria", texto: "Le han dicho que la operación es ambulatoria y podrá volver a casa el mismo día." },
    ejemploSinonimo: { palabra: "sin ingreso", texto: "Le han dicho que la operación es sin ingreso y podrá volver a casa el mismo día." },
    situacion: "salud",
  },
  {
    id: "asintomatico",
    palabra: "Asintomático",
    imagen: { id: 12293, alt: "Un médico dice que todo va bien" },
    definicion: "Tienes una enfermedad. Pero no notas nada.",
    sinonimos: ["sin síntomas"],
    ejemplo: { palabra: "asintomático", texto: "El análisis dio positivo, aunque Juan estaba asintomático." },
    ejemploSinonimo: { palabra: "sin síntomas", texto: "El análisis dio positivo, aunque Juan estaba sin síntomas." },
    situacion: "salud",
  },
  {
    id: "cronico",
    palabra: "Crónico",
    imagen: { id: 11252, alt: "Una persona enferma con medicinas" },
    definicion: "Dura mucho tiempo. No se cura enseguida.",
    sinonimos: ["de larga duración"],
    ejemplo: { palabra: "crónica", texto: "La diabetes es una enfermedad crónica que hay que controlar cada día." },
    ejemploSinonimo: { palabra: "de larga duración", texto: "La diabetes es una enfermedad de larga duración que hay que controlar cada día." },
    situacion: "salud",
  },
  {
    id: "benigno",
    palabra: "Benigno",
    imagen: { id: 37828, alt: "Una cara tranquila" },
    definicion: "No es grave. No es peligroso.",
    sinonimos: ["no grave", "inofensivo"],
    ejemplo: { palabra: "benigno", texto: "Los resultados dicen que el bulto es benigno y no hay de qué preocuparse." },
    ejemploSinonimo: { palabra: "no es grave", texto: "Los resultados dicen que el bulto no es grave y no hay de qué preocuparse." },
    situacion: "salud",
  },

  // --- Finanzas ---
  {
    id: "aval",
    palabra: "Aval",
    imagen: { id: 3062, alt: "La fachada de un banco con un cajero automático" },
    definicion: "Una persona promete pagar tu deuda si tú no puedes.",
    sinonimos: ["garantía", "garante"],
    ejemplo: { palabra: "aval", texto: "Mi padre me hizo de aval para el préstamo del coche." },
    ejemploSinonimo: { palabra: "garantía", texto: "Mi padre me hizo de garantía para el préstamo del coche." },
    situacion: "finanzas",
  },
  {
    id: "interes",
    palabra: "Interés",
    imagen: { id: 4630, alt: "Billetes y monedas de euro" },
    definicion: "Dinero extra que pagas por pedir dinero prestado.",
    sinonimos: ["recargo", "coste extra"],
    ejemplo: { palabra: "interés", texto: "El banco cobra un interés alto por este préstamo." },
    ejemploSinonimo: { palabra: "recargo", texto: "El banco cobra un recargo alto por este préstamo." },
    situacion: "finanzas",
  },
  {
    id: "domiciliar",
    palabra: "Domiciliar",
    imagen: { id: 16909, alt: "Dinero que se transfiere de un banco a otro" },
    definicion: "Hacer que el banco pague algo cada mes sin que tengas que hacer nada.",
    sinonimos: ["automatizar el pago", "poner en pago automático"],
    ejemplo: { palabra: "domiciliar", texto: "Puedes domiciliar la factura de la luz." },
    ejemploSinonimo: { palabra: "poner en pago automático", texto: "Puedes poner en pago automático la factura de la luz." },
    situacion: "finanzas",
  },
  {
    id: "saldo",
    palabra: "Saldo",
    imagen: { id: 4630, alt: "Billetes y monedas de euro" },
    definicion: "El dinero que tienes ahora mismo en tu cuenta del banco.",
    sinonimos: ["dinero disponible"],
    ejemplo: { palabra: "saldo", texto: "Puedes ver tu saldo en el cajero automático." },
    ejemploSinonimo: { palabra: "dinero disponible", texto: "Puedes ver tu dinero disponible en el cajero automático." },
    situacion: "finanzas",
  },
  {
    id: "plazo",
    palabra: "Plazo",
    imagen: { id: 9014, alt: "Alguien paga con tarjeta en una tienda" },
    definicion: "Cada una de las partes en las que pagas poco a poco algo caro.",
    sinonimos: ["cuota", "pago parcial"],
    ejemplo: { palabra: "plazos", texto: "Vamos a pagar la lavadora a plazos." },
    ejemploSinonimo: { palabra: "poco a poco", texto: "Vamos a pagar la lavadora poco a poco." },
    situacion: "finanzas",
  },

  // --- Vivienda ---
  {
    id: "hipoteca",
    palabra: "Hipoteca",
    imagen: { id: 3062, alt: "La fachada de un banco con un cajero automático" },
    definicion: "Dinero que te presta el banco para comprar una casa. Lo devuelves poco a poco durante muchos años.",
    sinonimos: ["préstamo para la vivienda"],
    ejemplo: { palabra: "hipoteca", texto: "Pagamos la hipoteca cada mes." },
    ejemploSinonimo: { palabra: "préstamo de la vivienda", texto: "Pagamos el préstamo de la vivienda cada mes." },
    situacion: "vivienda",
  },
  {
    id: "fianza",
    palabra: "Fianza",
    imagen: { id: 30480, alt: "Una mano entrega una moneda a otra mano" },
    definicion: "Dinero que dejas al dueño de la casa cuando alquilas. Te lo devuelve si todo está bien.",
    sinonimos: ["depósito", "garantía"],
    ejemplo: { palabra: "fianza", texto: "Al alquilar el piso, pagamos una fianza de un mes." },
    ejemploSinonimo: { palabra: "depósito", texto: "Al alquilar el piso, pagamos un depósito de un mes." },
    situacion: "vivienda",
  },
  {
    id: "empadronarse",
    palabra: "Empadronarse",
    imagen: { id: 3060, alt: "La fachada de un ayuntamiento" },
    definicion: "Apuntarte en el ayuntamiento para decir dónde vives.",
    sinonimos: ["registrarte en el ayuntamiento", "darte de alta"],
    ejemplo: { palabra: "empadronarte", texto: "Tienes que empadronarte en tu nuevo barrio." },
    ejemploSinonimo: { palabra: "registrarte", texto: "Tienes que registrarte en tu nuevo barrio." },
    situacion: "vivienda",
  },
  {
    id: "comunidad-vecinos",
    palabra: "Comunidad de vecinos",
    imagen: { id: 6241, alt: "Dos vecinos se saludan desde la ventana" },
    definicion: "Grupo de vecinos de un edificio. Deciden juntos y pagan una cuota para las zonas comunes.",
    sinonimos: ["vecinos del edificio"],
    ejemplo: { palabra: "comunidad de vecinos", texto: "La comunidad de vecinos decidió arreglar el ascensor." },
    ejemploSinonimo: { palabra: "vecinos del edificio", texto: "Los vecinos del edificio decidieron arreglar el ascensor." },
    situacion: "vivienda",
  },
  {
    id: "suministro",
    palabra: "Suministro",
    imagen: { id: 5995, alt: "Una factura con una firma" },
    definicion: "Servicio que llega a tu casa y que pagas cada mes, como la luz, el agua o el gas.",
    sinonimos: ["servicio"],
    ejemplo: { palabra: "suministro", texto: "Este mes ha subido el precio del suministro eléctrico." },
    ejemploSinonimo: { palabra: "servicio", texto: "Este mes ha subido el precio del servicio eléctrico." },
    situacion: "vivienda",
  },

  // --- Trabajo ---
  {
    id: "nomina",
    palabra: "Nómina",
    imagen: { id: 15986, alt: "Una mano recibe un billete" },
    definicion: "Papel que dice cuánto dinero ganas cada mes en tu trabajo.",
    sinonimos: ["recibo de sueldo", "recibo de salario"],
    ejemplo: { palabra: "nómina", texto: "Puedes ver tu nómina en el correo de la empresa." },
    ejemploSinonimo: { palabra: "recibo de sueldo", texto: "Puedes ver tu recibo de sueldo en el correo de la empresa." },
    situacion: "trabajo",
  },
  {
    id: "contrato",
    palabra: "Contrato",
    imagen: { id: 12317, alt: "Una mano firma un papel" },
    definicion: "Papel que firmas cuando empiezas un trabajo. Dice las condiciones.",
    sinonimos: ["acuerdo escrito", "acuerdo"],
    ejemplo: { palabra: "contrato", texto: "Firmó el contrato antes de empezar a trabajar." },
    ejemploSinonimo: { palabra: "acuerdo", texto: "Firmó el acuerdo antes de empezar a trabajar." },
    situacion: "trabajo",
  },
  {
    id: "baja",
    palabra: "Baja",
    imagen: { id: 28742, alt: "Una persona enferma en la cama" },
    definicion: "Permiso para no ir a trabajar porque estás enfermo. Lo firma el médico.",
    sinonimos: ["permiso médico"],
    ejemplo: { palabra: "baja", texto: "Está de baja porque se rompió una pierna." },
    ejemploSinonimo: { palabra: "permiso médico", texto: "Está de permiso médico porque se rompió una pierna." },
    situacion: "trabajo",
  },
  {
    id: "indemnizacion",
    palabra: "Indemnización",
    imagen: { id: 21531, alt: "Un jefe despide a un trabajador en la oficina" },
    definicion: "Dinero que te da la empresa cuando te despide.",
    sinonimos: ["compensación económica", "compensación"],
    ejemplo: { palabra: "indemnización", texto: "Le pagaron una indemnización al perder el trabajo." },
    ejemploSinonimo: { palabra: "compensación económica", texto: "Le pagaron una compensación económica al perder el trabajo." },
    situacion: "trabajo",
  },
  {
    id: "jornada",
    palabra: "Jornada",
    imagen: { id: 6012, alt: "Un horario semanal de lunes a domingo" },
    definicion: "Las horas que trabajas cada día.",
    sinonimos: ["horario de trabajo"],
    ejemplo: { palabra: "jornada", texto: "Su jornada laboral empieza a las ocho de la mañana." },
    ejemploSinonimo: { palabra: "horario de trabajo", texto: "Su horario de trabajo empieza a las ocho de la mañana." },
    situacion: "trabajo",
  },

  // --- Legal ---
  {
    id: "consentimiento",
    palabra: "Consentimiento",
    imagen: { id: 25698, alt: "Un médico con un papel y una persona pensando" },
    definicion: "Decir que sí a algo, después de entenderlo bien.",
    sinonimos: ["permiso", "autorización"],
    ejemplo: { palabra: "consentimiento", texto: "El médico pidió su consentimiento antes de la operación." },
    ejemploSinonimo: { palabra: "permiso", texto: "El médico pidió su permiso antes de la operación." },
    situacion: "legal",
  },
  {
    id: "poder-notarial",
    palabra: "Poder notarial",
    imagen: { id: 35413, alt: "Un notario junto a unos documentos firmados" },
    definicion: "Papel legal. Da permiso a otra persona para hacer trámites por ti.",
    sinonimos: ["autorización legal", "autorización ante notario"],
    ejemplo: { palabra: "poder notarial", texto: "Firmó un poder notarial para que su hija hiciera las gestiones del banco." },
    ejemploSinonimo: { palabra: "autorización legal", texto: "Firmó una autorización legal para que su hija hiciera las gestiones del banco." },
    situacion: "legal",
  },
  {
    id: "responsabilidad-civil",
    palabra: "Responsabilidad civil",
    imagen: { id: 16029, alt: "Un seguro de coche con la firma del dueño" },
    definicion: "Tener que pagar por un daño que le has hecho a otra persona.",
    sinonimos: ["pagar el daño causado", "el gasto del daño"],
    ejemplo: { palabra: "responsabilidad civil", texto: "El seguro cubre la responsabilidad civil si chocas con el coche." },
    ejemploSinonimo: { palabra: "el gasto del daño", texto: "El seguro cubre el gasto del daño si chocas con el coche." },
    situacion: "legal",
  },
  {
    id: "responsabilidad-penal",
    palabra: "Responsabilidad penal",
    imagen: { id: 4588, alt: "Un edificio de una cárcel" },
    definicion: "Tener que responder ante la ley por cometer un delito.",
    sinonimos: ["responder ante la justicia", "culpa penal"],
    ejemplo: { palabra: "responsabilidad penal", texto: "Puede tener responsabilidad penal si roba algo en la tienda." },
    ejemploSinonimo: { palabra: "que responder ante la justicia", texto: "Puede tener que responder ante la justicia si roba algo en la tienda." },
    situacion: "legal",
  },

  // --- Vida diaria ---
  {
    id: "reclamacion",
    palabra: "Reclamación",
    imagen: { id: 15529, alt: "Un papel de reclamación con una prenda tachada, un símbolo de euro y una cara enfadada" },
    definicion: "Un papel para avisar de un problema. Pides una solución o el dinero de vuelta.",
    sinonimos: ["queja formal", "protesta oficial"],
    ejemplo: { palabra: "reclamación", texto: "Puso una reclamación porque el pantalón nuevo estaba roto." },
    ejemploSinonimo: { palabra: "queja formal", texto: "Puso una queja formal porque el pantalón nuevo estaba roto." },
    situacion: "vida-diaria",
  },
  {
    id: "caducidad",
    palabra: "Caducidad",
    imagen: { id: 15503, alt: "Un envase de yogur con una fecha de caducidad marcada y una flecha que la señala" },
    definicion: "Marca el fin de la vida de un producto. Después de esa fecha, no lo uses.",
    sinonimos: ["fecha límite", "fecha de vencimiento"],
    ejemplo: { palabra: "fecha de caducidad", texto: "Antes de comer el yogur, mira la fecha de caducidad." },
    ejemploSinonimo: { palabra: "fecha límite", texto: "Antes de comer el yogur, mira la fecha límite." },
    situacion: "vida-diaria",
  },
  {
    id: "turno",
    palabra: "Turno",
    imagen: { id: 22190, alt: "Una mano coge un número de turno de una máquina dispensadora" },
    definicion: "Sacas un número al llegar a un lugar. Esperas y te llaman cuando toca.",
    sinonimos: ["número de espera", "vez"],
    ejemplo: { palabra: "turno", texto: "Sacó un turno en el banco y esperó su momento." },
    ejemploSinonimo: { palabra: "número de espera", texto: "Sacó un número de espera en el banco y esperó su momento." },
    situacion: "vida-diaria",
  },
  {
    id: "aforo",
    palabra: "Aforo",
    imagen: { id: 4688, alt: "Un cartel muestra que un lugar está lleno" },
    definicion: "Número máximo de personas en un lugar. Si se llega, no entra nadie más.",
    sinonimos: ["capacidad máxima", "límite de personas"],
    ejemplo: { palabra: "aforo completo", texto: "La sala tiene el aforo completo y ya no entra nadie más." },
    ejemploSinonimo: { palabra: "capacidad máxima", texto: "La sala tiene la capacidad máxima y ya no entra nadie más." },
    situacion: "vida-diaria",
  },
  {
    id: "franja-horaria",
    palabra: "Franja horaria",
    imagen: { id: 6012, alt: "Un horario con las horas marcadas para elegir un momento" },
    definicion: "Un tramo de horas para hacer algo. Se elige antes de una cita o entrega.",
    sinonimos: ["tramo de horas", "horario elegido"],
    ejemplo: { palabra: "franja horaria", texto: "Eligió una franja horaria de la tarde para recibir el paquete." },
    ejemploSinonimo: { palabra: "tramo de horas", texto: "Eligió un tramo de horas de la tarde para recibir el paquete." },
    situacion: "vida-diaria",
  },
  {
    id: "justificante",
    palabra: "Justificante",
    imagen: { id: 16873, alt: "Un papel de recibo" },
    definicion: "Un papel que demuestra algo. Por ejemplo, que fuiste a una cita.",
    sinonimos: ["comprobante", "papel que lo demuestra"],
    ejemplo: { palabra: "justificante", texto: "El colegio le pidió un justificante del médico." },
    ejemploSinonimo: { palabra: "comprobante", texto: "El colegio le pidió un comprobante del médico." },
    situacion: "vida-diaria",
  },
  {
    id: "incidencia",
    palabra: "Incidencia",
    imagen: { id: 5556, alt: "Un signo de exclamación que avisa de un problema" },
    definicion: "Un problema pequeño y no esperado. Se avisa de él para arreglarlo.",
    sinonimos: ["problema", "fallo"],
    ejemplo: { palabra: "incidencia", texto: "Avisó de una incidencia en la luz de su casa." },
    ejemploSinonimo: { palabra: "problema", texto: "Avisó de un problema en la luz de su casa." },
    situacion: "vida-diaria",
  },
  {
    id: "extravio",
    palabra: "Extravío",
    imagen: { id: 16159, alt: "Objetos perdidos guardados para que alguien los recoja" },
    definicion: "Perder algo sin saber dónde está. Puede ser una tarjeta o un documento.",
    sinonimos: ["pérdida", "objeto perdido"],
    ejemplo: { palabra: "extravío", texto: "Denunció el extravío de su documento de identidad." },
    ejemploSinonimo: { palabra: "pérdida", texto: "Denunció la pérdida de su documento de identidad." },
    situacion: "vida-diaria",
  },
  // --- "Pensión" is a real homograph: two unrelated meanings, same word.
  // Both entries use "palabra": "Pensión" on purpose, to test that the
  // index and the game handle two entries with the same headword. See
  // "Palabras con doble significado" in PRODUCT.md.
  {
    id: "pension-economica",
    palabra: "Pensión",
    imagen: { id: 14666, alt: "Una persona mayor jubilada" },
    definicion: "Dinero que da el Estado cada mes. Lo cobras cuando dejas de trabajar por edad.",
    sinonimos: ["paga de jubilación", "dinero mensual"],
    ejemplo: { palabra: "pensión", texto: "Cobra su pensión el día 1 de cada mes." },
    ejemploSinonimo: { palabra: "paga de jubilación", texto: "Cobra su paga de jubilación el día 1 de cada mes." },
    situacion: "finanzas",
  },
  {
    id: "pension-alojamiento",
    palabra: "Pensión",
    imagen: { id: 28363, alt: "Una casa pequeña de huéspedes" },
    definicion: "Una casa donde puedes dormir y comer pagando. Cuesta menos que un hotel.",
    sinonimos: ["casa de huéspedes", "hostal"],
    ejemplo: { palabra: "pensión", texto: "Se alojaron en una pensión cerca de la playa." },
    ejemploSinonimo: { palabra: "hostal", texto: "Se alojaron en un hostal cerca de la playa." },
    situacion: "vida-diaria",
  },
];
