/*
 * Sinonimia dictionary — ENGLISH.
 * This is a starter set that proves the multi-language setup works end to
 * end. It reuses pictograms already downloaded for the Spanish dictionary
 * (ARASAAC pictograms are language-neutral drawings), so no new images were
 * needed. Extend this file the same way js/data.es.js is extended — see the
 * field-by-field comments there. "situacion" must use the same shared keys:
 * "tramites", "salud", "vida-diaria", "finanzas", "vivienda", "trabajo", or
 * "legal" (see doc/en/SPEC.md; their on-screen labels live in js/i18n.js).
 */

window.DICCIONARIOS = window.DICCIONARIOS || {};
DICCIONARIOS.en = [
  {
    id: "rectify",
    palabra: "Rectify",
    imagen: { id: 28189, alt: "A hand corrects a mistake written on paper" },
    definicion: "To fix a mistake. To add what is missing.",
    sinonimos: ["fix", "correct"],
    ejemplo: { palabra: "rectify", texto: "The council asks you to rectify your form before Friday." },
    ejemploSinonimo: { palabra: "fix", texto: "The council asks you to fix your form before Friday." },
    situacion: "tramites",
  },
  {
    id: "notice",
    palabra: "Notice",
    imagen: { id: 2688, alt: "An envelope with a letter" },
    definicion: "An official letter. It tells you something.",
    sinonimos: ["letter"],
    ejemplo: { palabra: "notice", texto: "You received a notice from the tax office." },
    ejemploSinonimo: { palabra: "letter", texto: "You received a letter from the tax office." },
    situacion: "tramites",
  },
  {
    id: "waive",
    palabra: "Waive",
    imagen: { id: 7195, alt: "A person makes a stop gesture with their hand" },
    definicion: "To stop asking for something. To give up a claim.",
    sinonimos: ["give up", "drop"],
    ejemplo: { palabra: "waive", texto: "If you don't send the papers, you will waive your claim." },
    ejemploSinonimo: { palabra: "give up", texto: "If you don't send the papers, you will give up your claim." },
    situacion: "tramites",
  },
  {
    id: "appear",
    palabra: "Appear",
    imagen: { id: 11291, alt: "A judge with a gavel" },
    definicion: "To go to a place in person. A judge asks you to.",
    sinonimos: ["show up", "attend"],
    ejemplo: { palabra: "appear", texto: "The witness must appear in court next Monday." },
    ejemploSinonimo: { palabra: "show up", texto: "The witness must show up in court next Monday." },
    situacion: "tramites",
  },
  {
    id: "migraine",
    palabra: "Migraine",
    imagen: { id: 28651, alt: "A person with a headache" },
    definicion: "A strong headache.",
    sinonimos: ["bad headache"],
    ejemplo: { palabra: "migraine", texto: "The doctor gave her a pill for the migraine." },
    ejemploSinonimo: { palabra: "bad headache", texto: "The doctor gave her a pill for the bad headache." },
    situacion: "salud",
  },
  {
    id: "dyspnea",
    palabra: "Dyspnea",
    imagen: { id: 34409, alt: "A person breathing" },
    definicion: "When breathing feels hard. You feel short of air.",
    sinonimos: ["shortness of breath"],
    ejemplo: { palabra: "dyspnea", texto: "Climbing stairs gives him dyspnea these days." },
    ejemploSinonimo: { palabra: "shortness of breath", texto: "Climbing stairs gives him shortness of breath these days." },
    situacion: "salud",
  },
  {
    id: "edema",
    palabra: "Edema",
    imagen: { id: 3405, alt: "A swollen ankle" },
    definicion: "A body part swells up. Fluid builds up under the skin.",
    sinonimos: ["swelling"],
    ejemplo: { palabra: "edema", texto: "His ankle has an edema after the fall." },
    ejemploSinonimo: { palabra: "swelling", texto: "His ankle has a swelling after the fall." },
    situacion: "salud",
  },
  {
    id: "chronic",
    palabra: "Chronic",
    imagen: { id: 11252, alt: "A sick person with medicines" },
    definicion: "It lasts a long time. It does not go away quickly.",
    sinonimos: ["long-term"],
    ejemplo: { palabra: "chronic", texto: "Diabetes is a chronic illness you must manage every day." },
    ejemploSinonimo: { palabra: "long-term", texto: "Diabetes is a long-term illness you must manage every day." },
    situacion: "salud",
  },
  {
    id: "benign",
    palabra: "Benign",
    imagen: { id: 37828, alt: "A calm face" },
    definicion: "Not dangerous. Not serious.",
    sinonimos: ["harmless", "not serious"],
    ejemplo: { palabra: "benign", texto: "The results say the lump is benign, so there's nothing to worry about." },
    ejemploSinonimo: { palabra: "harmless", texto: "The results say the lump is harmless, so there's nothing to worry about." },
    situacion: "salud",
  },
  {
    id: "outpatient",
    palabra: "Outpatient",
    imagen: { id: 3116, alt: "A hospital" },
    definicion: "You don't need to stay in hospital. You go home the same day.",
    sinonimos: ["day-case"],
    ejemplo: { palabra: "outpatient", texto: "The surgery is outpatient care. She goes home the same day." },
    ejemploSinonimo: { palabra: "day-case", texto: "The surgery is day-case care. She goes home the same day." },
    situacion: "salud",
  },
  {
    id: "usufruct",
    palabra: "Usufruct",
    imagen: { id: 2317, alt: "A house" },
    definicion: "The right to use something and enjoy it. Even if it's not yours.",
    sinonimos: ["right to use"],
    ejemplo: { palabra: "usufruct", texto: "Grandma left her daughter the usufruct of the beach house." },
    ejemploSinonimo: { palabra: "right to use", texto: "Grandma left her daughter the right to use the beach house." },
    situacion: "legal",
  },

  // --- Finance, housing, employment, legal (one word each, to prove the new topics work) ---
  {
    id: "balance",
    palabra: "Balance",
    imagen: { id: 4630, alt: "Euro notes and coins" },
    definicion: "The money you have right now in your bank account.",
    sinonimos: ["available money"],
    ejemplo: { palabra: "balance", texto: "You can check your balance at the cash machine." },
    ejemploSinonimo: { palabra: "available money", texto: "You can check your available money at the cash machine." },
    situacion: "finanzas",
  },
  {
    id: "deposit",
    palabra: "Deposit",
    imagen: { id: 30480, alt: "One hand gives a coin to another hand" },
    definicion: "Money you leave with the landlord when you rent a home. You get it back if everything is fine.",
    sinonimos: ["security deposit"],
    ejemplo: { palabra: "deposit", texto: "We paid a deposit of one month when we rented the flat." },
    ejemploSinonimo: { palabra: "security deposit", texto: "We paid a security deposit of one month when we rented the flat." },
    situacion: "vivienda",
  },
  {
    id: "payslip",
    palabra: "Payslip",
    imagen: { id: 15986, alt: "A hand receives a bank note" },
    definicion: "A paper that says how much money you earn each month at work.",
    sinonimos: ["pay stub"],
    ejemplo: { palabra: "payslip", texto: "You can see your payslip in the company email." },
    ejemploSinonimo: { palabra: "pay stub", texto: "You can see your pay stub in the company email." },
    situacion: "trabajo",
  },
  {
    id: "consent",
    palabra: "Consent",
    imagen: { id: 25698, alt: "A doctor with a paper and a person thinking" },
    definicion: "Saying yes to something, after understanding it well.",
    sinonimos: ["permission", "agreement"],
    ejemplo: { palabra: "consent", texto: "The doctor asked for her consent before the operation." },
    ejemploSinonimo: { palabra: "permission", texto: "The doctor asked for her permission before the operation." },
    situacion: "legal",
  },
  {
    id: "civil-liability",
    palabra: "Civil liability",
    imagen: { id: 16029, alt: "Car insurance paper with the owner's signature" },
    definicion: "Having to pay for harm you caused to someone else.",
    sinonimos: ["paying for the harm caused"],
    ejemplo: { palabra: "civil liability", texto: "The insurance covers civil liability if you crash the car." },
    ejemploSinonimo: { palabra: "the cost of the harm", texto: "The insurance covers the cost of the harm if you crash the car." },
    situacion: "legal",
  },
  {
    id: "criminal-liability",
    palabra: "Criminal liability",
    imagen: { id: 4588, alt: "A prison building" },
    definicion: "Having to answer to the law for committing a crime.",
    sinonimos: ["answering to the law", "criminal guilt"],
    ejemplo: { palabra: "criminal liability", texto: "You can face criminal liability if you steal something from a shop." },
    ejemploSinonimo: { palabra: "having to answer to the law", texto: "You can face having to answer to the law if you steal something from a shop." },
    situacion: "legal",
  },

  // --- Everyday life ---
  {
    id: "overdue",
    palabra: "Overdue",
    imagen: { id: 37780, alt: "A clock showing something is late" },
    definicion: "Past the date it was due. It should have happened already.",
    sinonimos: ["late", "past the date"],
    ejemplo: { palabra: "overdue", texto: "The library book is overdue and needs to go back." },
    ejemploSinonimo: { palabra: "late", texto: "The library book is late and needs to go back." },
    situacion: "vida-diaria",
  },
  {
    id: "complimentary",
    palabra: "Complimentary",
    imagen: { id: 11582, alt: "A gift with a ribbon, meaning free of charge" },
    definicion: "Given for free. You do not pay for it.",
    sinonimos: ["free", "at no cost"],
    ejemplo: { palabra: "complimentary", texto: "The hotel offers a complimentary breakfast." },
    ejemploSinonimo: { palabra: "free", texto: "The hotel offers a free breakfast." },
    situacion: "vida-diaria",
  },
  {
    id: "duplicate",
    palabra: "Duplicate",
    imagen: { id: 11752, alt: "Two identical copies of the same paper" },
    definicion: "A second copy of the same paper. It is used if you lose the first one.",
    sinonimos: ["copy", "second copy"],
    ejemplo: { palabra: "duplicate", texto: "She asked the town hall for a duplicate of her certificate." },
    ejemploSinonimo: { palabra: "copy", texto: "She asked the town hall for a copy of her certificate." },
    situacion: "vida-diaria",
  },
  {
    id: "enclosed",
    palabra: "Enclosed",
    imagen: { id: 10325, alt: "An envelope with a letter inside" },
    definicion: "Sent together with the letter. It is inside the same envelope.",
    sinonimos: ["included", "inside"],
    ejemplo: { palabra: "enclosed", texto: "A form is enclosed with the letter." },
    ejemploSinonimo: { palabra: "included", texto: "A form is included with the letter." },
    situacion: "vida-diaria",
  },
  {
    id: "lost-property",
    palabra: "Lost property",
    imagen: { id: 16159, alt: "Lost items kept for someone to collect" },
    definicion: "A place for things people lost. You can go there to look for them.",
    sinonimos: ["lost and found"],
    ejemplo: { palabra: "lost property", texto: "She left her umbrella at the lost property office." },
    ejemploSinonimo: { palabra: "lost and found", texto: "She left her umbrella at the lost and found office." },
    situacion: "vida-diaria",
  },

  // "Pension" is a real homograph in English too: unrelated meanings,
  // same word. Both entries use "palabra": "Pension" on purpose, to test
  // that the index and the game handle two entries with the same
  // headword. See "Palabras con doble significado" in doc/en/SPEC.md.
  {
    id: "pension-payment",
    palabra: "Pension",
    imagen: { id: 14666, alt: "A retired older person" },
    definicion: "Money the state pays you every month. You get it when you retire.",
    sinonimos: ["retirement pay", "monthly payment"],
    ejemplo: { palabra: "pension", texto: "She receives her pension on the first day of the month." },
    ejemploSinonimo: { palabra: "retirement pay", texto: "She receives her retirement pay on the first day of the month." },
    situacion: "finanzas",
  },
  {
    id: "pension-guesthouse",
    palabra: "Pension",
    imagen: { id: 28363, alt: "A small guesthouse" },
    definicion: "A small house where you pay to sleep and eat. It costs less than a hotel.",
    sinonimos: ["guesthouse", "boarding house"],
    ejemplo: { palabra: "pension", texto: "They stayed in a pension near the beach." },
    ejemploSinonimo: { palabra: "guesthouse", texto: "They stayed in a guesthouse near the beach." },
    situacion: "vida-diaria",
  },
];
