/* ============================================================
   Sinonimia — Service Worker
   Three caches with different lifetimes:

   1. Shell cache (CACHE_NAME, tied to VERSION): the app shell listed in
      FILES, served cache-first. Add new shell files to FILES and bump
      VERSION whenever one of them changes.

   2. Data cache (DATA_CACHE, NOT tied to VERSION): the dictionary files
      generated by scripts/build-dictionary-data.js (js/dict.*), keyed by
      their content-hash ?v= URL. Because the URL changes only when the
      content changes, entries are immutable: a VERSION bump never
      re-downloads the dictionary, and a content batch only downloads the
      files whose hash changed. The list of files comes from
      js/dictionary-data.js, imported below (a change to it also makes the
      browser install a new service worker).

   3. Image cache (IMG_CACHE, NOT tied to VERSION): the ARASAAC pictograms
      (img/<id>.png). Stored as they are viewed; the whole set (~40 MB) is
      downloaded only when the person asks for it (message 'warm-images').

   The dictionary is NOT downloaded at install time: the page asks for it
   (message 'warm-dictionary') a few seconds after the first render, so the
   first visit is not slowed down. Once every file is stored the app works
   fully offline; until then, anything missing is fetched on demand.
   ============================================================ */
importScripts('./js/dictionary-data.js');

var VERSION = 'sinonimia-v216';

var FILES = [
  './',
  './index.html',
  './404.html',
  './manifest.json',
  './offline.html',
  './css/styles.css',
  './css/locale-picker.css',
  './js/i18n.js',
  './js/locale-picker-config.js',
  './js/locale-picker.js',
  './js/sw-register.js',
  './js/dictionary-data.js',
  './js/dictionary-loader.js',
  './js/bootstrap-i18n.js',
  './js/app.js',
  './img/logo.svg',
  './about/index.html',
  './about/about.js',
  './legal/index.html',
  './legal/privacidad.html',
  './team/index.html',
  './config/index.html',
  './config/config.js'
];

var CACHE_NAME = 'sinonimia-' + VERSION;
var DATA_CACHE = 'sinonimia-data';
var IMG_CACHE = 'sinonimia-img';

self.addEventListener('install', function (event) {
  event.waitUntil(
    caches.open(CACHE_NAME).then(function (cache) {
      // Put each file individually so one 404 on a future addition
      // does not abort the whole pre-cache pass — better to ship a
      // shell that's missing one entry than a shell that never
      // installs.
      return Promise.all(
        FILES.map(function (url) {
          return cache.add(url).catch(function (err) {
            // Surface the failing path in DevTools so an editor who
            // added a path that doesn't exist on disk sees the cause
            // immediately, instead of a silent "offline page" later.
            console.warn('[sw] pre-cache failed for ' + url + ': ' + (err && err.message ? err.message : err));
          });
        })
      );
    }).then(function () {
      return self.skipWaiting();
    })
  );
});

self.addEventListener('activate', function (event) {
  event.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(
        keys
          .filter(function (key) {
            return key.indexOf('sinonimia-') === 0 && key !== CACHE_NAME &&
              key !== DATA_CACHE && key !== IMG_CACHE;
          })
          .map(function (key) { return caches.delete(key); })
      );
    }).then(function () {
      return self.clients.claim();
    })
  );
});

self.addEventListener('fetch', function (event) {
  var request = event.request;
  // Only handle same-origin GETs. Anything cross-origin (ARASAAC
  // pictograms, etc.) is left to the network — the _headers rules
  // cache them at the edge, and the runtime never needs them offline.
  if (request.method !== 'GET') return;
  var url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Cache-first: try the cache, fall back to network, then to the
  // offline page. We deliberately cache the *full response* (with
  // status 200) so a 404/500 from the network never pollutes the
  // cache with an error page that would then be served offline.
  // Dictionary files: served from (and stored in) the data cache.
  if (url.pathname.indexOf('/js/dict.') === 0) {
    event.respondWith(cachedResponse(request, DATA_CACHE));
    return;
  }
  // Pictograms: stored as they are viewed and, if the person asks for it, all
  // at once. Their own cache, so a VERSION bump never throws them away.
  if (/^\/img\/\d+\.png$/.test(url.pathname)) {
    event.respondWith(cachedResponse(request, IMG_CACHE));
    return;
  }

  event.respondWith(
    caches.match(request).then(function (cached) {
      if (cached) return cached;
      return fetch(request).then(function (response) {
        // Only cache successful basic responses — opaque / errored
        // responses are skipped so the cache stays a faithful mirror
        // of what the server actually said.
        if (response && response.status === 200 && response.type === 'basic') {
          var copy = response.clone();
          caches.open(CACHE_NAME).then(function (cache) {
            cache.put(request, copy);
          });
        }
        return response;
      }).catch(function () {
        // No cache, no network — last resort is the offline page for
        // navigation requests. For sub-resources (CSS, JS, images)
        // we just propagate the failure so the browser surfaces a
        // standard network error.
        if (request.mode === 'navigate') {
          return caches.match('./offline.html');
        }
        return new Response('', { status: 504, statusText: 'Offline' });
      });
    })
  );
});

// --- Dictionary data (offline copy) -----------------------------------------

function cachedResponse(request, cacheName) {
  return caches.open(cacheName).then(function (cache) {
    return cache.match(request).then(function (cached) {
      if (cached) return cached;
      return fetch(request).then(function (response) {
        if (response && response.status === 200 && response.type === 'basic') {
          cache.put(request, response.clone());
        }
        return response;
      });
    });
  }).catch(function () {
    // Not saved yet and no network: the page shows its own "not saved" message
    // (or, for a pictogram, simply no picture).
    return new Response('', { status: 504, statusText: 'Offline' });
  });
}

// Every dictionary file as an absolute URL, the requested language first and
// the index (needed to draw anything) before the detail chunks.
function dictionaryUrls(language) {
  var manifest = self.SINONIMIA_DICTIONARY_DATA;
  var languages = Object.keys(manifest.languages);
  languages.sort(function (a, b) { return (a === language ? 0 : 1) - (b === language ? 0 : 1); });
  var urls = [];
  ['index', 'detail'].forEach(function (kind) {
    languages.forEach(function (lang) {
      manifest.languages[lang][kind].forEach(function (shard) {
        urls.push(new URL(shard.src, self.registration.scope).href);
      });
    });
  });
  return urls;
}

function broadcast(message) {
  return self.clients.matchAll({ includeUncontrolled: true }).then(function (clients) {
    clients.forEach(function (client) { client.postMessage(message); });
  });
}

var warming = null;

function warmDictionary(language) {
  if (warming) return warming;
  var urls = dictionaryUrls(language);
  var done = 0;
  var lastReported = 0;

  warming = caches.open(DATA_CACHE).then(function (cache) {
    var next = 0;
    function worker() {
      if (next >= urls.length) return Promise.resolve();
      var url = urls[next++];
      return cache.match(url).then(function (hit) {
        if (hit) return;
        return fetch(url).then(function (response) {
          if (!response || response.status !== 200) throw new Error('HTTP ' + (response && response.status));
          return cache.put(url, response);
        });
      }).then(function () {
        done++;
        if (done - lastReported >= 8) {
          lastReported = done;
          broadcast({ type: 'dictionary-offline', state: 'progress', done: done, total: urls.length });
        }
        return worker();
      });
    }
    // Four downloads at a time: fast enough, gentle on the connection.
    return Promise.all([worker(), worker(), worker(), worker()]).then(function () {
      // Everything current is stored: drop files of older dictionary versions.
      var wanted = {};
      urls.forEach(function (url) { wanted[url] = true; });
      return cache.keys().then(function (requests) {
        return Promise.all(requests.filter(function (req) { return !wanted[req.url]; })
          .map(function (req) { return cache['delete'](req); }));
      });
    }).then(function () {
      return broadcast({ type: 'dictionary-offline', state: 'done', done: urls.length, total: urls.length });
    });
  }).catch(function (err) {
    // Offline or a failed download: nothing is lost, the next visit retries
    // and only fetches what is still missing.
    console.warn('[sw] offline copy of the dictionary incomplete: ' + (err && err.message ? err.message : err));
  }).then(function () {
    warming = null;
  });
  return warming;
}

// --- Pictograms (optional offline copy) --------------------------------------
// Only when the person asks (the page sends 'warm-images'): ~40 MB, far more
// than the dictionary. Files already stored are skipped, so this also just
// completes the set after new words with new pictograms are added.

var warmingImages = null;

function warmImages() {
  if (warmingImages) return warmingImages;
  var ids = self.SINONIMIA_DICTIONARY_DATA.images;
  var urls = ids.map(function (id) {
    return new URL('img/' + id + '.png', self.registration.scope).href;
  });
  var done = 0;
  var lastReported = 0;

  warmingImages = caches.open(IMG_CACHE).then(function (cache) {
    var next = 0;
    function worker() {
      if (next >= urls.length) return Promise.resolve();
      var url = urls[next++];
      return cache.match(url).then(function (hit) {
        if (hit) return;
        return fetch(url).then(function (response) {
          if (!response || response.status !== 200) throw new Error('HTTP ' + (response && response.status));
          return cache.put(url, response);
        });
      }).then(function () {
        done++;
        if (done - lastReported >= 25) {
          lastReported = done;
          broadcast({ type: 'images-offline', state: 'progress', done: done, total: urls.length });
        }
        return worker();
      });
    }
    return Promise.all([worker(), worker(), worker(), worker(), worker(), worker()]).then(function () {
      // Drop pictograms no word uses any more.
      var wanted = {};
      urls.forEach(function (url) { wanted[url] = true; });
      return cache.keys().then(function (requests) {
        return Promise.all(requests.filter(function (req) { return !wanted[req.url]; })
          .map(function (req) { return cache['delete'](req); }));
      });
    }).then(function () {
      return broadcast({ type: 'images-offline', state: 'done', done: urls.length, total: urls.length });
    });
  }).catch(function (err) {
    console.warn('[sw] offline copy of the pictograms incomplete: ' + (err && err.message ? err.message : err));
    return broadcast({ type: 'images-offline', state: 'failed', done: done, total: urls.length });
  }).then(function () {
    warmingImages = null;
  });
  return warmingImages;
}

self.addEventListener('message', function (event) {
  var msg = event.data;
  if (msg && msg.type === 'warm-dictionary') {
    event.waitUntil(warmDictionary(msg.language));
  } else if (msg && msg.type === 'warm-images') {
    event.waitUntil(warmImages());
  }
});
