#!/usr/bin/env node
// scripts/build-head.js
// ---------------------
// Regenerates the <head> block between the `<!-- build:head:start -->` and
// `<!-- build:head:end -->` markers in `index.html` from a JSON config file
// (default: ./app.config.json).
//
// Why this exists:
// index.html carries SEO/Open Graph/Twitter metadata that is mostly static
// but gets tweaked often enough that hand-editing the HTML is error-prone
// (missing closing tags, broken quoting, accidentally touching JSON-LD).
// Putting the values in app.config.json and regenerating from here keeps
// the source of truth in one place and keeps the JSON-LD and the rest of
// the page untouched.
//
// Usage:
//   node scripts/build-head.js               # reads ./app.config.json, writes ./index.html
//   node scripts/build-head.js path/to.json  # custom config path (still writes ./index.html)
//
// Exit codes: 0 on success, 1 on any error (file missing, malformed JSON,
// no markers, malformed HTML between markers).
//
// Markers MUST be on their own lines. The script preserves everything
// before `<!-- build:head:start -->`, replaces the block up to and
// including `<!-- build:head:end -->`, and preserves the rest of the file
// verbatim.

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const configArg = process.argv[2];
const configPath = configArg
  ? path.resolve(ROOT, configArg)
  : path.join(ROOT, "app.config.json");
const indexPath = path.join(ROOT, "index.html");

const START_MARKER = "<!-- build:head:start -->";
const END_MARKER = "<!-- build:head:end -->";

function escapeAttr(value) {
  // Escape for a double-quoted HTML attribute: &, <, >, ", '.
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function buildHead(config) {
  const lines = [];

  lines.push("  <!-- ===== SEO: title, description, keywords, canonical, robots =====");
  lines.push("       Generated by scripts/build-head.js from app.config.json.");
  lines.push("       Do NOT edit the block between build:head:start and build:head:end");
  lines.push("       by hand -- it will be overwritten. Edit the config and re-run. -->");
  lines.push("  <title>" + escapeAttr(config.title) + "</title>");
  lines.push('  <meta name="description" content="' + escapeAttr(config.description) + '">');
  lines.push('  <meta name="keywords" content="' + escapeAttr(config.keywords) + '">');
  lines.push('  <meta name="author" content="' + escapeAttr(config.author) + '">');
  lines.push('  <meta name="robots" content="index,follow,max-image-preview:large">');
  lines.push('  <link rel="canonical" href="' + escapeAttr(config.domain) + '/">');
  lines.push('  <link rel="alternate" hreflang="es" href="' + escapeAttr(config.domain) + '/?lang=es">');
  lines.push('  <link rel="alternate" hreflang="en" href="' + escapeAttr(config.domain) + '/?lang=en">');
  lines.push('  <link rel="alternate" hreflang="x-default" href="' + escapeAttr(config.domain) + '/">');

  // PWA manifest — optional. When config.manifest is null/empty, the
  // <link> is omitted entirely (today's behaviour: no PWA, no manifest
  // tag). When set, it points at the relative path so the site works
  // both at the domain root and under any preview subpath.
  if (config.manifest) {
    lines.push('  <link rel="manifest" href="' + escapeAttr(config.manifest) + '">');
  }

  // Open Graph — og:image is optional. If ogImageAsset is null/empty, the
  // og:image / twitter:image tags are omitted entirely (the meta block in
  // index.html no longer references a missing asset, which would 404 in
  // crawlers' previews). When set, og:image points at
  // https://<domain>/<ogImageAsset>.
  if (config.ogImageAsset) {
    const ogImageUrl = escapeAttr(config.domain) + "/" + escapeAttr(config.ogImageAsset);
    lines.push("");
    lines.push("  <!-- ===== Open Graph (Facebook, LinkedIn, Discord, WhatsApp previews) ===== -->");
    lines.push('  <meta property="og:type" content="website">');
    lines.push('  <meta property="og:site_name" content="' + escapeAttr(config.ogSiteName) + '">');
    lines.push('  <meta property="og:locale" content="es_ES">');
    lines.push('  <meta property="og:locale:alternate" content="en_US">');
    lines.push('  <meta property="og:title" content="' + escapeAttr(config.title) + '">');
    lines.push('  <meta property="og:description" content="' + escapeAttr(config.ogDescription) + '">');
    lines.push('  <meta property="og:url" content="' + escapeAttr(config.domain) + '/">');
    lines.push('  <meta property="og:image" content="' + ogImageUrl + '">');
    lines.push('  <meta property="og:image:width" content="1200">');
    lines.push('  <meta property="og:image:height" content="630">');
    lines.push('  <meta property="og:image:alt" content="' + escapeAttr(config.ogImageAlt) + '">');

    lines.push("");
    lines.push("  <!-- ===== Twitter Card ===== -->");
    lines.push('  <meta name="twitter:card" content="summary_large_image">');
    lines.push('  <meta name="twitter:title" content="' + escapeAttr(config.title) + '">');
    lines.push('  <meta name="twitter:description" content="' + escapeAttr(config.twitterDescription) + '">');
    lines.push('  <meta name="twitter:image" content="' + ogImageUrl + '">');
  }

  if (config.themeColor) {
    lines.push("");
    lines.push("  <!-- ===== Theme / appearance ===== -->");
    lines.push('  <meta name="theme-color" content="' + escapeAttr(config.themeColor) + '">');
  }
  if (config.colorScheme) {
    lines.push('  <meta name="color-scheme" content="' + escapeAttr(config.colorScheme) + '">');
  }

  return lines.join("\n");
}

function main() {
  if (!fs.existsSync(configPath)) {
    console.error("build-head: config not found: " + configPath);
    process.exit(1);
  }
  let config;
  try {
    config = JSON.parse(fs.readFileSync(configPath, "utf8"));
  } catch (err) {
    console.error("build-head: malformed JSON in " + configPath + " (" + err.message + ")");
    process.exit(1);
  }
  for (const required of ["title", "description", "keywords", "author", "domain"]) {
    if (!config[required]) {
      console.error("build-head: missing required field \"" + required + "\" in config");
      process.exit(1);
    }
  }

  if (!fs.existsSync(indexPath)) {
    console.error("build-head: index.html not found at " + indexPath);
    process.exit(1);
  }
  const html = fs.readFileSync(indexPath, "utf8");

  const startIdx = html.indexOf(START_MARKER);
  const endIdx = html.indexOf(END_MARKER);
  if (startIdx === -1 || endIdx === -1 || endIdx <= startIdx) {
    console.error("build-head: markers not found in index.html (need both \"" +
      START_MARKER + "\" and \"" + END_MARKER + "\" on their own lines)");
    process.exit(1);
  }

  // Sanity check: the character right after the start marker must be a
  // newline, and the line right before the end marker must contain only
  // whitespace. This prevents the script from being run against a file
  // where someone removed the newlines around the markers.
  if (html.charAt(startIdx + START_MARKER.length) !== "\n" ||
      html.charAt(startIdx + START_MARKER.length + 1) !== "\n") {
    console.error("build-head: start marker must be followed by a blank line (got: \"" +
      JSON.stringify(html.substr(startIdx + START_MARKER.length, 2)) + "\")");
    process.exit(1);
  }
  if (html.charAt(endIdx - 1) !== "\n" || html.charAt(endIdx - 2) !== "\n") {
    console.error("build-head: end marker must be preceded by a blank line");
    process.exit(1);
  }

  const headBlock = buildHead(config);
  // Replace from the line AFTER the start marker to the line BEFORE the end
  // marker (i.e. drop both markers + the block between them, then insert
  // the new block). Layout: <newline><marker>\n\n<old>\n\n<marker><newline>
  const before = html.substring(0, startIdx + START_MARKER.length) + "\n\n";
  const after = "\n\n" + html.substring(endIdx);
  const next = before + headBlock + after;

  if (next === html) {
    console.log("build-head: index.html already in sync with config, nothing to write");
    process.exit(0);
  }
  fs.writeFileSync(indexPath, next, "utf8");
  console.log("build-head: regenerated " + path.relative(ROOT, indexPath) + " from " +
    path.relative(ROOT, configPath));
}

main();