#!/usr/bin/env node
/*
 * scripts/limpiar-cache.js — housekeeping for Sinonimia's local cache/scratch dirs.
 *
 * Sinonimia has two developer-only directories that grow over time:
 *
 *   scripts/.cache/    — frequency-word lists downloaded by
 *                        scripts/candidatos-corpus.js. Re-downloaded on
 *                        next run, so safe to remove.
 *   scripts/.scratch/  — one-off exploration scripts the maintainer drops
 *                        here during corpus/content work. NOT regenerated
 *                        automatically, so this script NEVER touches it.
 *
 * This script only handles .cache/.scratch is excluded on purpose:
 *   - .scratch/ contains the maintainer's work-in-progress queries.
 *     Deleting it automatically is worse than letting it grow.
 *   - The cache is rebuilt by the next `candidatos-corpus.js` run.
 *   - Both dirs are already in .gitignore, so they don't bloat git.
 *
 * Usage:
 *   node scripts/limpiar-cache.js            # dry-run (default): shows what would be removed
 *   node scripts/limpiar-cache.js --apply    # actually removes the files
 *   node scripts/limpiar-cache.js --help
 *
 * Why a dry-run by default: deleting things is irreversible, and a
 * maintainer who runs this from muscle memory shouldn't have to think
 * twice. Same pattern as `git clean`'s default.
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const TARGETS = [
  {
    dir: path.join(__dirname, ".cache"),
    note: "frequency-word list cache (regenerated by scripts/candidatos-corpus.js)",
  },
];

function bytesHuman(n) {
  if (n < 1024) return n + " B";
  if (n < 1024 * 1024) return (n / 1024).toFixed(1) + " KiB";
  return (n / (1024 * 1024)).toFixed(2) + " MiB";
}

function listDirRecursive(dir) {
  const out = [];
  if (!fs.existsSync(dir)) return out;
  function walk(d) {
    for (const entry of fs.readdirSync(d, { withFileTypes: true })) {
      const full = path.join(d, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.isFile()) out.push(full);
    }
  }
  walk(dir);
  return out;
}

function emptyDir(dir) {
  if (!fs.existsSync(dir)) return;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      emptyDir(full);
      fs.rmdirSync(full);
    } else if (entry.isFile()) {
      fs.unlinkSync(full);
    }
  }
  // Also remove the root itself so the directory disappears entirely.
  // The next run will recreate it via mkdirSync({ recursive: true }).
  fs.rmdirSync(dir);
}

const args = process.argv.slice(2);
if (args.includes("--help") || args.includes("-h")) {
  console.log(
    "Usage:\n" +
    "  node scripts/limpiar-cache.js            # dry-run (default): shows what would be removed\n" +
    "  node scripts/limpiar-cache.js --apply    # actually removes the files\n" +
    "  node scripts/limpiar-cache.js --help\n"
  );
  process.exit(0);
}
const apply = args.includes("--apply");

let totalFiles = 0;
let totalBytes = 0;
const summary = [];

for (const target of TARGETS) {
  const files = listDirRecursive(target.dir);
  const bytes = files.reduce((sum, f) => sum + fs.statSync(f).size, 0);
  totalFiles += files.length;
  totalBytes += bytes;
  summary.push({ dir: target.dir, note: target.note, files: files, bytes: bytes });
}

console.log("=== Sinonimia — cache cleanup ===\n");
console.log("Note: scripts/.scratch/ is intentionally NOT touched — it holds");
console.log("      the maintainer's work-in-progress query scripts.\n");

if (totalFiles === 0) {
  console.log("Nothing to remove. All listed directories are already empty or absent.");
  process.exit(0);
}

for (const s of summary) {
  const rel = path.relative(ROOT, s.dir);
  console.log(rel + "  (" + s.files.length + " file(s), " + bytesHuman(s.bytes) + ")");
  console.log("  " + s.note);
  if (s.files.length && apply) {
    s.files.forEach((f) => console.log("  - " + path.relative(ROOT, f)));
  }
  console.log("");
}

if (!apply) {
  console.log(
    "DRY RUN — no files were removed. Re-run with --apply to actually delete them.\n" +
    "Total: " + totalFiles + " file(s), " + bytesHuman(totalBytes) + "."
  );
  process.exit(0);
}

for (const s of summary) {
  emptyDir(s.dir);
}

console.log(
  "Removed " + totalFiles + " file(s) (" + bytesHuman(totalBytes) + ").\n" +
  "scripts/.cache/ will be rebuilt automatically on the next\n" +
  "node scripts/candidatos-corpus.js run."
);
